SCCXF = \
stop.f \
stopwithout201.f \
closefile.f \
openfile.f \
readinput.f \
includefilename.f \
keystart.f \
splitline.f \
restartshort.f \
skip.f \
allocation.f \
inputerror.f \
getnewline.f \
userelements.f \
nidentk.f \
betacalinput.f \
designvariabless.f \
boundarys.f \
buckles.f \
cloads.f \
elements.f \
inputwarning.f \
dloads.f \
elastics.f \
dynamics.f \
noelfiles.f \
noelsets.f \
nodes.f \
steps.f \
statics.f \
loadaddp.f \
loadadd.f \
bodyadd.f \
elprints.f \
materials.f \
nodeprints.f \
gen3delem.f \
multistages.f \
sensitivitys.f \
objectives.f \
solidsections.f \
densitys.f \
transformatrix.f \
nident.f \
linkdissimilar.f \
triangulate.f \
changekon.f \
dsort.f \
attach_2d.f \
distattach_2d.f \
straighteq2d.f \
isortii.f \
near2d.f \
genmodes.f \
fillknotmpc.f \
gen3dtemp.f \
gen3dsurf.f \
gen3dfrom1d.f \
gen3dfrom2d.f \
gen3dnor.f \
norshell3.f \
norshell4.f \
norshell6.f \
norshell8.f \
gen3dtruss.f \
usermpc.f \
bounadd.f \
knotmpc.f \
gen3dmembrane.f \
rs.f \
shape6tri.f \
shape4q.f \
shape3tri.f \
shape8q.f \
ident.f \
gen3dmpc.f \
gen3dforc.f \
gen3dconnect.f \
nident2.f \
cident.f \
gen3dboun.f \
mpcrem.f \
forcadd.f \
selectcyclicsymmetrymodess.f \
spcmatch.f 




SCCXC = \
strcmp1.c \
strcmp2.c \
strcpy1.c \
u_calloc.c \
u_realloc.c \
readinput.c \
u_free.c \
rho.c \
writeheading.c \
linstatic.c


SCCXCXX = umat_dl.cpp